language: ruby
cache: bundler

rvm:
  - 2.1.1

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script:
  - CODECLIMATE_REPO_TOKEN=44d7688de8e1b567b4af25ec5083c2cc0a355ab911192a7cbefd1ea25b2ffd3d RAILS_ENV=test bundle exec rake --trace db:migrate test

before_script:
  - mysql -e 'create database devise_token_auth_test'
  - psql -c 'create database devise_token_auth_test' -U postgres
